# Generated by Django 3.0.6 on 2020-05-17 22:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pntnum', models.IntegerField()),
                ('panoid', models.CharField(max_length=80)),
                ('panodate', models.CharField(max_length=80)),
                ('greenview', models.FloatField(max_length=6)),
                ('url0', models.CharField(blank=True, max_length=200, null=True)),
                ('url60', models.CharField(blank=True, max_length=200, null=True)),
                ('url120', models.CharField(blank=True, max_length=200, null=True)),
                ('url180', models.CharField(blank=True, max_length=200, null=True)),
                ('url240', models.CharField(blank=True, max_length=200, null=True)),
                ('url300', models.CharField(blank=True, max_length=200, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'greenmodel',
            },
        ),
    ]
