# Generated by Django 3.0.6 on 2020-05-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GEO', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greenmodel',
            new_name='Toledo',
        ),
        migrations.AlterModelOptions(
            name='toledo',
            options={'verbose_name_plural': 'Toledo'},
        ),
    ]
